apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful_start_stop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graceful_start_stop
  template:
    metadata:
      labels:
        app: graceful_start_stop
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: module2
          image: look4xiaodong/cloudnative-module2:0.1
          args:
            - /module2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
              initialDelaySeconds: 10
              periodSeconds: 15
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo httpserver started"]
            preStop:
              exec:
                command: ["/bin/sh","-c","echo httpserver exited"]
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          volumes:
            - name: varlog
              emptyDir: { }
    status:
      qosClass: Guaranteed

---
apiVersion: v1
kind: Service
metadata:
  name: graceful_start_stop
spec:
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: graceful_start_stop
  type: NodePort