apiVersion: apps/v1
kind: Deployment
metadata:
  name: graceful-start-stop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graceful_start_stop
  template:
    metadata:
      labels:
        app: graceful_start_stop
    spec:
      terminationGracePeriodSeconds: 300
      containers:
        - name: module2
          image: look4xiaodong/cloudnative-module2:0.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: varlog
              mountPath: /var/log
          resources:
            requests:
              memory: 128Mi
              cpu: 500m
            limits:
              cpu: 1
              memory: 1Gi
          livenessProbe:
            exec:
              command:
                - cat
                - /module2
            initialDelaySeconds: 30
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "echo httpserver started  > /usr/share/message"]
            preStop:
              exec:
                command: ["/bin/sh","-c","echo httpserver exited  > /usr/share/message"]
      volumes:
      - name: varlog
        emptyDir: { }

---
apiVersion: v1
kind: Service
metadata:
  name: graceful-start-stop
spec:
  ports:
    - name: "80"
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: graceful_start_stop
  type: NodePort